title: Stackbit Exto Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Plio-Pleistocene food webs webs of the Turkana Basin
color_scheme: dark
accent_color: green
header:
  title: Turkana Foodwebs
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: People
      url: /portfolio/
      style: link
    - label: Projects
      url: /blog/
      style: link
    - label: About
      url: /about/
      style: link
footer:
  content: '&copy; W. Andrew Barr'
  has_social: false
  social_links:
    - label: Instagram
      url: 'https://www.instagram.com/'
      style: icon
      icon_class: fa-instagram
      new_window: true
    - label: Dribbble
      url: 'https://dribbble.com/'
      style: icon
      icon_class: fa-dribbble
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: icon
      icon_class: fa-linkedin
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
